// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Contact struct {
	ContactID   uuid.UUID `json:"contact_id"`
	FirstName   string    `json:"first_name"`
	LastName    string    `json:"last_name"`
	PhoneNumber string    `json:"phone_number"`
	Street      string    `json:"street"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Format struct {
	FormatID          uuid.UUID `json:"format_id"`
	FormatName        string    `json:"format_name"`
	FormatDescription string    `json:"format_description"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type Game struct {
	GameID   uuid.UUID `json:"game_id"`
	GameName string    `json:"game_name"`
}

type Hero struct {
	HeroID    uuid.UUID     `json:"hero_id"`
	HeroName  string        `json:"hero_name"`
	FormatID  uuid.NullUUID `json:"format_id"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

type Match struct {
	MatchID         uuid.UUID      `json:"match_id"`
	GameID          uuid.NullUUID  `json:"game_id"`
	MatchName       sql.NullString `json:"match_name"`
	Player1ID       uuid.NullUUID  `json:"player1_id"`
	Player2ID       uuid.NullUUID  `json:"player2_id"`
	WinnerID        uuid.NullUUID  `json:"winner_id"`
	LoserID         uuid.NullUUID  `json:"loser_id"`
	Player1Decklist sql.NullString `json:"player1_decklist"`
	Player2Decklist sql.NullString `json:"player2_decklist"`
	Player1Hero     uuid.NullUUID  `json:"player1_hero"`
	Player2Hero     uuid.NullUUID  `json:"player2_hero"`
	MatchDate       time.Time      `json:"match_date"`
	FormatID        uuid.NullUUID  `json:"format_id"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	InProgress      sql.NullBool   `json:"in_progress"`
}

type Ranking struct {
	RankingID   uuid.UUID     `json:"ranking_id"`
	UserID      uuid.NullUUID `json:"user_id"`
	GameID      uuid.NullUUID `json:"game_id"`
	FormatID    uuid.NullUUID `json:"format_id"`
	EloScore    sql.NullInt32 `json:"elo_score"`
	LastUpdated sql.NullTime  `json:"last_updated"`
}

type RefreshToken struct {
	ID           int32     `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	RefreshToken string    `json:"refresh_token"`
	Expiry       time.Time `json:"expiry"`
}

type User struct {
	UserID            uuid.UUID    `json:"user_id"`
	UserName          string       `json:"user_name"`
	UserEmail         string       `json:"user_email"`
	CreatedAt         time.Time    `json:"created_at"`
	UpdatedAt         time.Time    `json:"updated_at"`
	Wins              int32        `json:"wins"`
	Losses            int32        `json:"losses"`
	Ties              int32        `json:"ties"`
	Elo               int32        `json:"elo"`
	HashedPassword    string       `json:"hashed_password"`
	PasswordChangedAt sql.NullTime `json:"password_changed_at"`
}
