// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: tokens.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createToken = `-- name: CreateToken :exec
INSERT INTO tokens (hash, user_id, expiry, scope) 
VALUES ($1, $2, $3, $4)
`

type CreateTokenParams struct {
	Hash   []byte    `json:"hash"`
	UserID uuid.UUID `json:"user_id"`
	Expiry time.Time `json:"expiry"`
	Scope  string    `json:"scope"`
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) error {
	_, err := q.exec(ctx, q.createTokenStmt, createToken,
		arg.Hash,
		arg.UserID,
		arg.Expiry,
		arg.Scope,
	)
	return err
}

const deleteAllTokensForUser = `-- name: DeleteAllTokensForUser :exec
DELETE FROM tokens
WHERE scope =$1 and user_id = $2
`

type DeleteAllTokensForUserParams struct {
	Scope  string    `json:"scope"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteAllTokensForUser(ctx context.Context, arg DeleteAllTokensForUserParams) error {
	_, err := q.exec(ctx, q.deleteAllTokensForUserStmt, deleteAllTokensForUser, arg.Scope, arg.UserID)
	return err
}
